# Diese Datei aktiviert den "Sponsor"-Button auf GitHub
# Passe die URLs an deine Accounts an

# github: [username]
# patreon: username
# open_collective: username
# ko_fi: username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# otechie: username
# lfx_crowdfunding: project-name
# custom: ['https://www.buymeacoffee.com/username']
